/** Generated by scripts/export-user-vault-templates.mjs from ownerId RW9S6zkgrxYAbbhLuBp9eCkEMbD2 — edit freely. */

/** Starter tags copied into each new account (owned by the user; fully editable). */
export const DEFAULT_TAGS: ReadonlyArray<{
  name: string;
  color: string;
  category: string;
}> = [
  { name: "30-Min Meal", color: "#f97316", category: "Time" },
  { name: "Air fryer", color: "#78716c", category: "Method" },
  { name: "American", color: "#3b82f6", category: "Cuisine" },
  { name: "Asian", color: "#f97316", category: "Cuisine" },
  { name: "BBQ ♨️", color: "#ef4444", category: "Method" },
  { name: "Baked", color: "#ef4444", category: "Method" },
  { name: "Breakfast", color: "#f97316", category: "Occasion" },
  { name: "Brunch", color: "#ec4899", category: "Occasion" },
  { name: "Comfort Food", color: "#ec4899", category: "Diet / Nutrition" },
  { name: "Dinner", color: "#ef4444", category: "Occasion" },
  { name: "Favorites", color: "#eab308", category: "Other" },
  { name: "Greek", color: "#3b82f6", category: "Cuisine" },
  { name: "Grilled", color: "#ef4444", category: "Method" },
  { name: "Guest Favorite", color: "#8b5cf6", category: "Other" },
  { name: "Healthy", color: "#22c55e", category: "Diet / Nutrition" },
  { name: "High-Protein", color: "#3b82f6", category: "Diet / Nutrition" },
  { name: "Indian", color: "#eab308", category: "Cuisine" },
  { name: "Italian", color: "#22c55e", category: "Cuisine" },
  { name: "Kid Approved", color: "#06b6d4", category: "Other" },
  { name: "Kid-Friendly", color: "#06b6d4", category: "Occasion" },
  { name: "Kids", color: "#ec4899", category: "Other" },
  { name: "Lunch", color: "#eab308", category: "Occasion" },
  { name: "Meal Prep", color: "#0d9488", category: "Time" },
  { name: "Mediterranean", color: "#06b6d4", category: "Cuisine" },
  { name: "Mexican", color: "#ef4444", category: "Cuisine" },
  { name: "Middle Eastern", color: "#8b5cf6", category: "Cuisine" },
  { name: "No-Cook", color: "#22c55e", category: "Method" },
  { name: "One-Pot", color: "#06b6d4", category: "Method" },
  { name: "Pan-Fried", color: "#f97316", category: "Method" },
  { name: "Party", color: "#8b5cf6", category: "Occasion" },
  { name: "Pressure Cooker", color: "#0d9488", category: "Method" },
  { name: "Quick (≤20 min)", color: "#eab308", category: "Time" },
  { name: "Quick N' Easy", color: "#eab308", category: "Other" },
  { name: "Savory", color: "#f97316", category: "Flavor" },
  { name: "Snack", color: "#22c55e", category: "Occasion" },
  { name: "Spicy", color: "#ef4444", category: "Flavor" },
  { name: "Stir-Fry", color: "#eab308", category: "Method" },
  { name: "Sweet", color: "#8b5cf6", category: "Flavor" },
  { name: "To Try", color: "#3b82f6", category: "Other" },
  { name: "Vegan", color: "#22c55e", category: "Diet / Nutrition" },
  { name: "Vegetarian", color: "#22c55e", category: "Diet / Nutrition" },
  { name: "Vietnamese", color: "#78716c", category: "Cuisine" },
  { name: "Winter", color: "#3b82f6", category: "Other" },
  { name: "Νηστίσιμο", color: "#eab308", category: "Other" },
];

/** Starter recipe categories copied into each new account (owned by the user; fully editable). */
export const DEFAULT_CATEGORIES: ReadonlyArray<{
  name: string;
  description: string;
  icon: string;
}> = [
  { name: "Appetizer & Snack", description: "Dips, bruschetta, spring rolls, and finger food", icon: "cherry" },
  { name: "Beverage", description: "Smoothie, cocktail, lemonade", icon: "cup-soda" },
  { name: "Breakfast & Brunch", description: "Pancakes, eggs, smoothie bowls, and brunch plates", icon: "egg-fried" },
  { name: "Dessert & Baking", description: "Cookies, cake, mousse", icon: "cookie" },
  { name: "Meat & Poultry", description: "Roasted chicken, steak, meatballs", icon: "beef" },
  { name: "Other", description: "Anything that doesn't fit elsewhere", icon: "utensils" },
  { name: "Pasta & Noodles", description: "Spaghetti, pad thai, ramen, lasagna", icon: "utensils" },
  { name: "Pie & Tart", description: "Quiche, pot pie, galette, and savory tarts", icon: "cooking-pot" },
  { name: "Pizza & Flatbread", description: "Homemade pizza, focaccia, and flatbreads", icon: "pizza" },
  { name: "Rice & Grains", description: "Risotto, fried rice, pilaf", icon: "wheat" },
  { name: "Salad", description: "Caesar, Greek, grain bowls", icon: "leaf" },
  { name: "Sandwich & Wrap", description: "Burrito, gyro, club sandwich", icon: "sandwich" },
  { name: "Sauce & Condiment", description: "Pesto, vinaigrettes, salsa, and dips", icon: "bean" },
  { name: "Seafood & Fish", description: "Grilled salmon, shrimp scampi", icon: "fish" },
  { name: "Side Dish", description: "Roasted vegetables, coleslaw, mashed potatoes", icon: "utensils" },
  { name: "Soup", description: "Lentil soup, chili, minestrone", icon: "soup" },
];
